services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: atom
      DB_PASS: atom
      DB_NAME: tododb
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: atom
      POSTGRES_PASSWORD: atom
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: